DROP TABLE REPLY cascade CONSTRAINTS;
DROP TABLE BOARD cascade CONSTRAINTS;
DROP TABLE MEMBER cascade CONSTRAINTS;
DROP TABLE BOARD_FILE cascade CONSTRAINTS;
DROP TABLE CHAT cascade CONSTRAINTS;
DROP TABLE MESSAGE cascade CONSTRAINTS;
DROP TABLE PARTICIPANT cascade CONSTRAINTS;
DROP TABLE MEMBER_ROLE cascade CONSTRAINTS;

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE MEMBER_ROLE_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE BOARD_FILE_SEQ;
DROP SEQUENCE CHAT_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE PARTICIPANT_SEQ;
DROP SEQUENCE REPLY_SEQ;


-- MEMBER 테이블 생성
CREATE TABLE MEMBER
(
    ID              NUMBER(10) NOT NULL,
    EMAIL           VARCHAR2(50) unique ,
    NAME            VARCHAR2(20) NOT NULL,
    PASSWORD        VARCHAR2(100) NOT NULL,
    PHONE           VARCHAR2(50) ,
    REGI_ID         VARCHAR2(50)   NOT NULL,
    REGI_DT         DATE         NOT NULL,
    UPDT_ID         VARCHAR2(50)   NOT NULL,
    UPDT_DT         DATE         NOT NULL,
    CONSTRAINT MEMBER_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1;

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.ID IS '회원 번호';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.REGI_ID IS '등록아이디';
COMMENT ON COLUMN MEMBER.REGI_DT IS '등록날짜';
COMMENT ON COLUMN MEMBER.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN MEMBER.UPDT_DT IS '수정날짜';


-- MEMBER_ROLE 테이블 생성
CREATE TABLE MEMBER_ROLE
(
    ID          NUMBER(11)     NOT NULL ,
    MEMBER_ID   VARCHAR2(50)   NOT NULL ,
    ROLE_NAME   VARCHAR2(100)  NOT NULL ,
    PRIMARY KEY (id),
    FOREIGN KEY (MEMBER_ID)REFERENCES MEMBER(EMAIL)
);


CREATE SEQUENCE MEMBER_ROLE_SEQ
    START WITH 1
    INCREMENT BY 1;



-- BOARD 테이블 생성
CREATE TABLE BOARD
(
    ID                 NUMBER(10)        NOT NULL,
    BOARD_CATEGORY     VARCHAR2(20)      NOT NULL,
    BOARD_TITLE        VARCHAR2(100)     NOT NULL,
    BOARD_CONTENT      VARCHAR2(4000)    NOT NULL,
    BOARD_COUNT        NUMBER(10)        NOT NULL,
    BOARD_RE_REF       NUMBER(10)        NOT NULL,
    BOARD_RE_LEV       NUMBER(10)        NOT NULL,
    BOARD_RE_SEQ       NUMBER(10)        NOT NULL,
    REGI_ID            VARCHAR2(50)       NOT NULL,
    REGI_DT            DATE              NOT NULL,
    UPDT_ID            VARCHAR2(50)      NOT NULL,
    UPDT_DT            DATE              NOT NULL,
    CONSTRAINT BOARD_PK PRIMARY KEY (ID),
    FOREIGN KEY (REGI_ID)REFERENCES MEMBER(EMAIL)
);

CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1;

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.ID IS '게시판번호';
COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS '카테고리';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '내용';
COMMENT ON COLUMN BOARD.BOARD_COUNT IS '읽은 수';
COMMENT ON COLUMN BOARD.BOARD_RE_REF IS '참조 번호';
COMMENT ON COLUMN BOARD.BOARD_RE_LEV IS '참조 레벨';
COMMENT ON COLUMN BOARD.BOARD_RE_SEQ IS '참조 순서';
COMMENT ON COLUMN BOARD.REGI_ID IS '등록아이디';
COMMENT ON COLUMN BOARD.REGI_DT IS '등록날짜';
COMMENT ON COLUMN BOARD.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN BOARD.UPDT_DT IS '수정날짜';


-- REPLY 테이블 생성
CREATE TABLE REPLY
(
    ID           NUMBER(10)       NOT NULL,
    BOARD_ID     NUMBER(10)       NOT NULL,
    MEMBER_ID    VARCHAR2(50)       NOT NULL,
    CONTENT      VARCHAR2(100)    NOT NULL,
    REGI_ID      VARCHAR2(50)       NOT NULL,
    REGI_DT      DATE             NOT NULL,
    UPDT_ID      VARCHAR2(50)       NOT NULL,
    UPDT_DT      DATE             NOT NULL,
    CONSTRAINT COMMENT_PK PRIMARY KEY (ID),
    FOREIGN KEY (BOARD_ID)REFERENCES BOARD(ID),
    FOREIGN KEY (MEMBER_ID)REFERENCES MEMBER(EMAIL)
);

COMMENT ON TABLE REPLY IS '게시판 댓글';
COMMENT ON COLUMN REPLY.ID IS '댓글 번호';
COMMENT ON COLUMN REPLY.BOARD_ID IS '게시판 번호';
COMMENT ON COLUMN REPLY.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN REPLY.CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.REGI_ID IS '등록아이디';
COMMENT ON COLUMN REPLY.REGI_DT IS '등록날짜';
COMMENT ON COLUMN REPLY.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN REPLY.UPDT_DT IS '수정날짜';

CREATE SEQUENCE REPLY_SEQ
    START WITH 1
    INCREMENT BY 1;




-- BOARD_FILE 테이블 생성
CREATE TABLE BOARD_FILE
(
    ID               NUMBER          NOT NULL,
    BOARD_ID         VARCHAR2(50)    NOT NULL,
    FILE_NAME        VARCHAR2(50)    NOT NULL,
    FILE_ORIGINAL    VARCHAR2(50)    NOT NULL,
    REGI_ID          VARCHAR2(50)      NOT NULL,
    REGI_DT          DATE            NOT NULL,
    UPDT_ID          VARCHAR2(50)      NOT NULL,
    UPDT_DT          DATE            NOT NULL,
    CONSTRAINT BOARD_FILE_PK PRIMARY KEY (ID),
    FOREIGN KEY (BOARD_ID)REFERENCES MEMBER(EMAIL)
);

COMMENT ON TABLE BOARD_FILE IS '게시판 파일';
COMMENT ON COLUMN BOARD_FILE.ID IS '파일 번호';
COMMENT ON COLUMN BOARD_FILE.BOARD_ID IS '게시판 번호';
COMMENT ON COLUMN BOARD_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN BOARD_FILE.FILE_ORIGINAL IS '원파일명';
COMMENT ON COLUMN BOARD_FILE.REGI_ID IS '등록아이디';
COMMENT ON COLUMN BOARD_FILE.REGI_DT IS '등록날짜';
COMMENT ON COLUMN BOARD_FILE.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN BOARD_FILE.UPDT_DT IS '수정날짜';

CREATE SEQUENCE BOARD_FILE_SEQ
    START WITH 1
    INCREMENT BY 1;



-- CHAT 테이블 생성
CREATE TABLE CHAT
(
    ID           NUMBER(10)    NOT NULL,
    REGI_ID      VARCHAR2(50)    NOT NULL,
    REGI_DT      DATE          NOT NULL,
    UPDT_ID      VARCHAR2(50)    NOT NULL,
    UPDT_DT      DATE          NOT NULL,
    CONDITION    NUMBER(1)     NOT NULL,
    CONSTRAINT CHAT_PK PRIMARY KEY (ID),
    FOREIGN KEY (REGI_ID) REFERENCES MEMBER(EMAIL),
    FOREIGN KEY (UPDT_ID)REFERENCES MEMBER(EMAIL)
);

COMMENT ON TABLE CHAT IS '채팅방';
COMMENT ON COLUMN CHAT.ID IS '채팅방 번호';
COMMENT ON COLUMN CHAT.CONDITION IS '0 : 상담대기, 1 : 상담중, 2 : 상담완료, 3 : 상담미완료(종료) ';
COMMENT ON COLUMN CHAT.REGI_ID IS '등록아이디';
COMMENT ON COLUMN CHAT.REGI_DT IS '등록날짜';
COMMENT ON COLUMN CHAT.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN CHAT.UPDT_DT IS '수정날짜';

CREATE SEQUENCE CHAT_SEQ
    START WITH 1
    INCREMENT BY 1;



-- MESSAGE 테이블 생성
CREATE TABLE MESSAGE
(
    ID         NUMBER(10)       NOT NULL,
    CHAT_ID    NUMBER(10)       NOT NULL,
    CONTENT    VARCHAR2(500)    NOT NULL,
    REGI_ID    VARCHAR2(50)       NOT NULL,
    REGI_DT    DATE             NOT NULL,
    UPDT_ID    VARCHAR2(50)       NOT NULL,
    UPDT_DT    DATE             NOT NULL,
    CONSTRAINT MESSAGE_PK PRIMARY KEY (ID),
    FOREIGN KEY (CHAT_ID)REFERENCES CHAT(ID),
    FOREIGN KEY (REGI_ID) REFERENCES MEMBER(EMAIL),
    FOREIGN KEY (UPDT_ID)REFERENCES MEMBER(EMAIL)
);

COMMENT ON TABLE MESSAGE IS '메시지';
COMMENT ON COLUMN MESSAGE.ID IS '메시지 번호';
COMMENT ON COLUMN MESSAGE.CHAT_ID IS '채팅번호';
COMMENT ON COLUMN MESSAGE.CONTENT IS '내용';
COMMENT ON COLUMN MESSAGE.REGI_ID IS '등록아이디';
COMMENT ON COLUMN MESSAGE.REGI_DT IS '등록날짜';
COMMENT ON COLUMN MESSAGE.UPDT_ID IS '수정아이디';
COMMENT ON COLUMN MESSAGE.UPDT_DT IS '수정날짜';


CREATE SEQUENCE MESSAGE_SEQ
    START WITH 1
    INCREMENT BY 1;



-- PARTICIPANT 테이블 생성
CREATE TABLE PARTICIPANT
(
    ID         NUMBER(10)    NOT NULL,
    CHAT_ID    NUMBER(10)    NOT NULL,
    REGI_ID    VARCHAR2(50)    NOT NULL,
    REGI_DT    DATE          NOT NULL,
    CONSTRAINT PARTICIPANT_PK PRIMARY KEY (ID),
    FOREIGN KEY (CHAT_ID)REFERENCES CHAT(ID)
);


COMMENT ON TABLE PARTICIPANT IS '참가자';
COMMENT ON COLUMN PARTICIPANT.ID IS '참가자 번호';
COMMENT ON COLUMN PARTICIPANT.CHAT_ID IS '채팅번호';
COMMENT ON COLUMN PARTICIPANT.REGI_ID IS '등록아이디';
COMMENT ON COLUMN PARTICIPANT.REGI_DT IS '등록날짜';

CREATE SEQUENCE PARTICIPANT_SEQ
    START WITH 1
    INCREMENT BY 1;

COMMIT;


